export interface Alert {
    id: string;
    type: 'critical' | 'high' | 'medium' | 'low';
    title: string;
    location: string;
    zone: string;
    timestamp: Date;
    vehicles: number;
    confidence: number;
    status: 'active' | 'responding' | 'resolved' | 'escalated';
    cameraId: string;
    coordinates: { lat: number; lng: number };
    description: string;
    actions: string[];
    images: any[];
    severity: 'minor' | 'moderate' | 'severe' | 'fatal';
    responseTime: number;
    assignedUnits: string[];
    casualties: number;
    responsibleDepartment: string;
    city?: string;
    district?: string;
    stateName?: string;
    roadHighwayId?: string;
    vehicleTypes?: string[];
    infrastructureInvolved?: string[];
    injuredCount?: number;
    criticalInjuries?: number;
    fatalities?: number;
    trappedPersons?: boolean;
    weatherCondition?: string;
    visibilityLevel?: string;
    roadCondition?: string;
    fireFlag?: boolean;
    fuelLeakFlag?: boolean;
    chemicalHazardFlag?: boolean;
    agenciesToNotify?: string[];
    reportGenerated: boolean;
    handledBy: string;
    weather?: string;
    incidentType: string;
    roadConditionVal?: string;
}
